version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"  
    environment:
      - N8N_HOST=n8n.${DOMAIN}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https                 
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.${DOMAIN}/
      - GENERIC_TIMEZONE=Asia/Kolkata
      - N8N_ENFORCE_SETTINGS_FILE_FOR_ALLOWED_IP_ADDRESSES_IN_WEBHOOKS=false
      
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168        
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: