services:
  nextcloud-db:
    image: mariadb:10.11
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /home/penguin/purrbrews-infra/data/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: always
    depends_on:
      - nextcloud-db
    ports:
      - 8080:80 
    volumes:
      - /home/penguin/purrbrews-infra/data/nextcloud/app:/var/www/html 
      - /media/storage/nextcloud_data:/var/www/html/data 
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER=${NC_ADMIN}
      - NEXTCLOUD_ADMIN_PASSWORD=${NC_PASS}
      - NEXTCLOUD_TRUSTED_DOMAINS=drive.${DOMAIN}