services:
  nextcloud-db:
    image: mariadb:10.11
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    env_file:
      - ../env
    volumes:
      - ${DATA_DIR}/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud-redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    restart: always
    env_file:
      - ../env

  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: always
    env_file:
      - ../env
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    ports:
      - 8001:80 
    volumes:
      - ${DATA_DIR}/nextcloud/app:/var/www/html 
      - ${MEDIA_DIR}/nextcloud/data:/var/www/html/data 
    environment:
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER=${NC_ADMIN}
      - NEXTCLOUD_ADMIN_PASSWORD=${NC_PASS}
      - NEXTCLOUD_TRUSTED_DOMAINS=drive.${DOMAIN}
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PORT=6379
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=tls
      - SMTP_AUTHTYPE=LOGIN
      - SMTP_NAME=${EMAIL_USERNAME}
      - SMTP_PASSWORD=${EMAIL_PASSWORD}
      - MAIL_FROM_ADDRESS=nextcloud
      - MAIL_DOMAIN=${DOMAIN}
      - TRUSTED_PROXIES=192.168.0.10
      - OVERWRITEHOST=drive.${DOMAIN}
      - OVERWRITEPROTOCOL=https
      - APACHE_DISABLE_REWRITE_IP=1

  nextcloud-cron:
    image: nextcloud:latest
    container_name: nextcloud-cron
    restart: always
    env_file:
      - ../env
    volumes:
      - ${DATA_DIR}/nextcloud/app:/var/www/html
      - ${MEDIA_DIR}/nextcloud/data:/var/www/html/data
    entrypoint: /cron.sh
    depends_on:
      - nextcloud-db
      - nextcloud-redis