#!/usr/bin/env bash
#
# oidc-secret-sync.sh -- pushes each OIDC client's PLAINTEXT secret
# (generated by ./generate-secrets.sh, stored here in
# authelia/secrets.env.local) out over SSH to the node that actually
# runs that app. Added 2026-09-06, replacing the manual "copy this value
# into that node's secrets.env.local" handoff -- confirmed sieve's SSH
# key is already authorized (as `barista`) on every other fleet node.
# generate-secrets.sh's own printed summary table is still accurate and
# still there as a manual fallback if this script can't reach a node for
# some reason.
#
# The secret value never touches a command line, shell history, or an
# intermediate file on either end: it's piped over SSH's own stdin
# straight into set-secret.sh (deployed once per node -- that file has
# no secrets in it, just the idempotent set-or-skip logic) running on the
# remote side. `ps` on either host never shows a plaintext value as an
# argument.
#
# Idempotent -- a target key that's already a real (non-REPLACE_ME,
# non-empty) value is left alone by set-secret.sh, same philosophy as
# this script's own set_if_absent. Safe to re-run.
#
# roastery is structurally different from every other node here (your
# own Windows/WSL2 machine, not a Debian fleet node -- see
# roastery/README.md) -- it's included below on the assumption its SSH
# setup mirrors the others, but that's NOT independently confirmed the
# way it is for sieve/silo/cellar/percolator/mochaPot. If it can't be
# reached, this script just reports a connection failure for that one
# row and moves on -- fall back to a manual copy for Jellyfin's secret if
# so, nothing else breaks.
#
# Usage:
#   ./oidc-secret-sync.sh                # all apps
#   ./oidc-secret-sync.sh vikunja immich  # just these (space-separated)
#   ./oidc-secret-sync.sh --dry-run       # show what would happen, touch nothing
#
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SSH_USER="barista"
REMOTE_REPO_ROOT="/opt/purrbrews/stacks"
SECRET_FILE="${DIR}/authelia/secrets.env.local"
SSH_OPTS=(-o StrictHostKeyChecking=accept-new -o ConnectTimeout=8)

get_value() {
  local file="$1" key="$2" line=""
  [[ -f "$file" ]] || return 0
  line="$(grep -E "^${key}=" "$file" 2>/dev/null || true)"
  [[ -z "$line" ]] && return 0
  printf '%s\n' "$line" | tail -n1 | cut -d= -f2-
}

# app-name : node-hostname : app-dir-under-that-node : ENV_VAR_PREFIX
APPS=(
  "vikunja:mochaPot:vikunja:VIKUNJA"
  "mealie:mochaPot:mealie:MEALIE"
  "immich:mochaPot:immich:IMMICH"
  "freshrss:mochaPot:freshrss:FRESHRSS"
  "actualbudget:mochaPot:actualbudget:ACTUALBUDGET"
  "nextcloud:percolator:nextcloud:NEXTCLOUD"
  "paperless:percolator:paperless:PAPERLESS"
  "homeassistant:percolator:homeassistant:HOMEASSISTANT"
  "vaultwarden:cellar:vaultwarden:VAULTWARDEN"
  "komodo:silo:komodo:KOMODO"
  "jellyfin:roastery:jellyfin:JELLYFIN"
)

DRY_RUN=false
FILTER=()
for arg in "$@"; do
  if [[ "$arg" == "--dry-run" ]]; then
    DRY_RUN=true
  else
    FILTER+=("$arg")
  fi
done

declare -A helper_deployed

deploy_helper() {
  local node="$1"
  [[ -n "${helper_deployed[$node]:-}" ]] && return 0
  if [[ "$DRY_RUN" == true ]]; then
    echo "    (dry-run: would scp set-secret.sh to ${node}.lan)"
  else
    scp -q "${SSH_OPTS[@]}" "${DIR}/set-secret.sh" "${SSH_USER}@${node}.lan:~/.purrbrews-set-secret.sh"
    ssh "${SSH_OPTS[@]}" "${SSH_USER}@${node}.lan" "chmod 700 ~/.purrbrews-set-secret.sh"
  fi
  helper_deployed[$node]=1
}

echo "Pushing OIDC client secrets from authelia/secrets.env.local to their own nodes..."
[[ "$DRY_RUN" == true ]] && echo "(--dry-run: nothing will actually be touched)"
echo

for entry in "${APPS[@]}"; do
  IFS=: read -r app node appdir prefix <<< "$entry"

  if [[ ${#FILTER[@]} -gt 0 ]]; then
    match=false
    for f in "${FILTER[@]}"; do [[ "$f" == "$app" ]] && match=true; done
    [[ "$match" == true ]] || continue
  fi

  value="$(get_value "$SECRET_FILE" "${prefix}_OIDC_CLIENT_SECRET")"
  if [[ -z "$value" ]]; then
    echo "SKIP ${app}: no ${prefix}_OIDC_CLIENT_SECRET found in authelia/secrets.env.local -- run ./generate-secrets.sh first"
    continue
  fi

  remote_path="${REMOTE_REPO_ROOT}/${node}/${appdir}/secrets.env.local"
  echo "==> ${app} (${node}.lan): ${remote_path} -> ${prefix}_OIDC_CLIENT_SECRET"
  deploy_helper "$node"

  if [[ "$DRY_RUN" == true ]]; then
    echo "    (dry-run: would ssh in and set this key, value withheld)"
    continue
  fi

  if ! ssh "${SSH_OPTS[@]}" "${SSH_USER}@${node}.lan" \
      "~/.purrbrews-set-secret.sh '${remote_path}' '${prefix}_OIDC_CLIENT_SECRET'" <<< "$value"; then
    echo "    ! failed to reach or update ${node}.lan -- fall back to a manual copy for this one"
  fi
done

echo
echo "Done. On each node that got an update, re-run that node's own"
echo "./generate-secrets.sh to confirm it no longer flags the value as"
echo "still-needed, then ./render-configs.sh before bringing that app up"
echo "with its new OIDC config."
